name: Deploy Nexus

on:
    push:
        branches: [main] # Triggers when you push to the main branch

jobs:
    install-packages:
        runs-on: ubuntu-latest
        steps:
            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "24"

            - name: Install PM2
              run: npm install -g pm2

            - name: Install Git
              run: sudo apt-get install git -y

            - name: Install npm
              run: sudo apt-get install npm -y

    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Deploy via SSH
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USER }}
                  key: ${{ secrets.SSH_KEY }}
                  port: ${{ secrets.SSH_PORT }}
                  script: |
                      # Clone the repository if it doesn't exist
                      if [ ! -d "Nexus" ]; then
                        git clone git@github.com:AnAnonymousHB/Nexus.git
                      fi

                      # Navigate to the bot directory
                      cd Nexus

                      # Pull latest changes
                      git pull origin main

                      # Install dependencies and build
                      npm install
                      npm run build

                      # Restart the bot with PM2
                      pm2 restart nexus --update-env
